# Generated by Django 3.0.7 on 2020-06-26 18:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_remove_tutorial_registered_users'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='account',
            name='registered_tutorials',
            field=models.ManyToManyField(related_name='registered_tutorials', to='tutorials.Tutorial'),
        ),
    ]
