# Generated by Django 3.0.7 on 2020-06-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200626_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='registered_tutorials',
        ),
    ]
