# Generated by Django 3.0.7 on 2020-06-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_registered_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='registered_tutorial',
        ),
    ]
