# Generated by Django 3.0.7 on 2020-06-26 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0002_remove_tutorial_registered_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='registered_users',
            field=models.ManyToManyField(related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
