# Generated by Django 3.0.7 on 2020-06-26 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0003_tutorial_registered_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
