# Generated by Django 3.0.7 on 2020-06-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_tutorial_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='registered_users',
        ),
    ]
