# Generated by Django 3.0.7 on 2020-06-26 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tutorial',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 15, 56, 12, 42269), editable=False),
        ),
    ]
