# Generated by Django 3.0.7 on 2020-06-26 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_auto_20200626_1648'),
        ('comment', '0002_auto_20200626_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_comments', to='tutorials.Tutorial'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 16, 48, 49, 211161), editable=False),
        ),
    ]
