# Generated by Django 3.0.7 on 2020-06-26 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200626_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 16, 49, 58, 598935), editable=False),
        ),
    ]
